### ISSUE TITLE
I made a similar tool 

### ISSUE THREAD

**Issue by onny** [makefu/prison-break#2]
Hey,
I made a similar tool which checks for new wifi connections via D-BUS (iwd supported) and it triggers a hyperpotamus script for the authentication process.
It might be a bit more easy to configure and use.
Feel free to contribute if you want, maybe you'll like my approach.
Blog post over here: https://blog.project-insanity.org/2020/08/24/auto-authenticate-to-public-wifis-or-test-hotspots/
Best regards
Jonas

**Comment by makefu** [comment]
Hey! Thanks for the hint, at first glace, hyerpotamus looks very cool and the integration with dbus is quite nice. I will definitely check out your implementation!
